version: "3.8"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ~/HoustanConfigs/HomeAssistant:/config
    ports:
      - 8123:8123
    restart: unless-stopped