ports:
  - port: 0001-8999
    onOpen: ignore

additionalRepositories:
  - url: https://github.com/JesseRigon/HoustanData.git
    checkoutLocation: HoustanData

workspaceLocation: Houstan/main.code-workspace # Relative to /workspace dir